### ISSUE TITLE
the installation is failing

### ISSUE THREAD

**Issue by TuPhanRLI** [OpenEnergyPlatform/oem2orm#1]
the syntax : pip install -i https://test.pypi.org/simple/ oem2orm
doesn't work properly 
error message  "No module named  'jmespath'"

**Comment by jh-RLI** [comment]
Thanks! This is deprecated information. I will replace this with the new package distribution. 

`
pip install oem2orm
`

**Comment by jh-RLI** [comment]
closed in release v0.2.6

**Comment by jh-RLI** [comment]
I think omi was missing in the package dependency list. #8 will fix this.
