### ISSUE TITLE
Metadata to ORM feature

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oem2orm#2]
I requested a feature to convert the _oemetadata_ JSON to ORM.
This makes the publication of data easy.

My collegue @henhuy developed this package _md2orm_ and @jh-RLI pushed it to this repo.

Planned toolchain for **Data Upload:**

![2020-03-09_MD2OEP-upload_0 2](https://user-images.githubusercontent.com/14353512/76298634-112fb600-62ba-11ea-9fa1-632e21aa878e.png)

1. Create **metadata** from data
2. Create ORM from metadata using `MD2ORM`
3. Create [ERM](https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model) usind `ERAlchemy`
4. Upload data to **OEP** using `oedialect`
5. Upload **metadata** and add **tags**

**Comment by henhuy** [comment]
We can close, right?

**Comment by jh-RLI** [comment]
Yes! But maybe we should document the diagrams that @Ludee created. I think he got them from somewhere, but I'll put them in our "cloud" for now and then close this topic.
