### ISSUE TITLE
Error while updating metadata on OEP is not forwarded

### ISSUE THREAD

**Issue by henhuy** [OpenEnergyPlatform/oem2orm#29]
When updating metadata on the OEP via `oep_oedialect_oem2orm.api_updateMdOnTable` `status_code` of response is checked whether it is `200`. If an error occurs (aka `status_code != "200"`) the error gets logged, but no error is thrown.
Thus, a user cannot know whether updated worked or not.
I would suggest throwing a `MetadataError``with information from response if upload fails.

**Comment by henhuy** [comment]
Found another bug in the same function!
status_code is checked against `"200"`, but status codes are integers.
Thus, checking will always fail! As only error was only logged, this did not affect uploading.
Fixed error in PR as well!

**Comment by jh-RLI** [comment]
Great :D that must have been some c&p action I did - I will make a general review of oem2orm somewhat soon, I think some of these helper functions are made from code I just took from old tutorials quite some time ago.
