### ISSUE TITLE
Improve error and status messages when uploading tables

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/oem2orm#31]
Uploading tables with oem2orm, e.g. using the [script ](https://openenergy-platform.org/tutorials/jupyter/OEP_Upload_Process_Data_and_Metadata_oem2orm/)from the tutorial section, is not user-friendly due a lack of helpful error messages.

- Inform the user which table is processed. Currently, when the table creation fails and throws a bad/unspecific error message, it is not clear which table is the reason (in case of uploading a bulk of tables)
- Improve the error messages when violating the postgresql naming conventions for `column headers` and `resources-name`. Relates to  https://github.com/OpenEnergyPlatform/oem2orm/issues/16#issuecomment-1326405579

**Comment by jh-RLI** [comment]
FYI @chrwm you want to have a look at the error massages, they are implemented in this [function](https://github.com/OpenEnergyPlatform/oeplatform/blob/4766d8878fba7a3b1745a92fab038ae7b9059cf9/api/actions.py#L821-L914). There are multiple APIErrors raised that return the error string.
